alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: simonecorsi.dev
    type: PRIMARY
    zone: simonecorsi.dev
envs:
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: simonecorsi-dev
      match:
        path:
          prefix: /
name: simonecorsi-dev
region: fra
static_sites:
  - name: web
    github:
      deploy_on_push: true
      branch: main
      repo: simonecorsi/simonecorsi.dev
    dockerfile_path: Dockerfile.static
    output_dir: /app/dist
