name: Build and Deploy to Netlify

# When workflow is triggered
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$GH_TOKEN" > .env.local
          npm ci
          npm run build
          npm run export

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./dist"
          production-branch: main
          production-deploy: true
          github-token: ${{ secrets.GH_PESONAL_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_APIKEY }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_ID }}
        timeout-minutes: 1
