name: Deploy on DigitalOcean

on:
  schedule:
    - cron: '00 01 * * *'
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GH_PESONAL_TOKEN }}
          env: production

      - uses: actions/checkout@v4

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: simonecorsi-dev
          token: ${{ secrets.DO_ACTION_TOKEN }}

      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          env_url: https://simonecorsi.dev
          token: ${{ secrets.GH_PESONAL_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
