name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PESONAL_TOKEN }}
          persist-credentials: false

      - name: Install dependencies
        run: npm i

      - name: Test build before deploy
        run: npm run export

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PESONAL_TOKEN }}
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_COMMITTER_NAME: ${{ github.actor }}
